### PR TITLE
Add initial files

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Overview of changes:

* c987090 Add basic documentation 
* 339709a Add pre-commit hooks 
* 7f321be Create CHANGELOG.md file 
* cbb72c8 Add dotfiles and config files 
* f472e91 Configure Jest 
* c910379 Remove boilerplate static files 
* 9a43d0b Add common react hooks 
* f36ac76 Add tiny localization framework 
* 70f2520 Remove boilerplate files 
* 53017ad Add base styles 
* 6e21025 Add TypeScript typing utils 
* 4fdaf46 Fix TypeScript errors 
* feb29ea Add internationalization helpers 
* f453727 Add a Loading Context 
* 6b7f73a Add a React Error Boundary 
* af8f0e4 Fix failing test 
* cc353f7 Add issue templates 
* dd66787 Add Chrome Extension manifest v3 file
* e777219 Add GitHub action for running unit tests

### CODE REVIEW

**Comment by Durbatuluk1701** [comment]
Looking good. Need to build/run locally and then I'll approve.

**Comment by Durbatuluk1701** [comment]
For some reason it seems to be failing the Jest tests locally for me at "src/components/Atoms/Internationalization.tsx:107:27" with the error: " RangeError: Value dateTimeField out of range for Intl.DisplayNames options property type at new DisplayNames (<anonymous>)"
I feel like this might be something about my computer because the error really makes no sense, clearly 'dateTimeField' is in the range of possibilities for that type.

**Comment by maxxxxxdlp** [comment]
I believe you are running an older version of Node.js.
Please upgrade to Node.js 18 (which is the current release) and the issue will be fixed

For reference, here is how successful output would look like - https://github.com/maxxxxxdlp/calendar-stats/runs/8271512945?check_suite_focus=true#step:8:1

**Comment by Durbatuluk1701** [comment]
Good call, that fixed it!

**Pull request merged**
